export const productData = [
  {
    id: 1,
    title: "",
    cetagory: "Men's Shoes",
    price: "210",
    lessPrice: "",
    offPrice: "",
    img: "/p1/ph1.webp",
    pLink: "/product/1",
  },
  {
    id: 2,
    title: "Air Jordan XXXVII Low",
    cetagory: "Basketball Shoes",
    price: "$175",
    lessPrice: "",
    offPrice: "",
    img: "/p2/ph1.webp",
  },
  {
    id: 3,
    title: "Jordan 6 Rings",
    cetagory: "Men's Shoes",
    price: "$170",
    lessPrice: "",
    offPrice: "",
    img: "/p3/ph1.webp",
  },
  {
    id: 4,
    title: "Nike Alpha Menace Elite 3 RW",
    cetagory: "Men's Football Cleats",
    price: "$200",
    lessPrice: "",
    offPrice: "",
    img: "/p4/ph1.webp",
  },
  {
    id: 5,
    title: "Nike Vapor Edge 360 VC",
    cetagory: "Men's Football Cleats",
    price: "$84.97",
    lessPrice: "$120",
    offPrice: "29% off",
    img: "/p5/ph1.webp",
  },
  {
    id: 6,
    title: "Nike Alpha Menace Pro 3",
    cetagory: "Men's Football Cleats",
    price: "$100",
    lessPrice: "",
    offPrice: "",
    img: "/p6/ph1.webp",
  },
  {
    id: 7,
    title: "Nike Zoom Fly 5",
    cetagory: "Men's Running Shoes",
    price: "$118.97",
    lessPrice: "$170",
    offPrice: "30%",
    img: "/p7/ph1.webp",
  },

  {
    id: 8,
    title: "Nike Invincible 3",
    cetagory: "Men's Road Running Shoes",
    price: "$180",
    lessPrice: "",
    offPrice: "",
    img: "/p8/ph1.webp",
  },
  {
    id: 9,
    title: "Nike Free Run 2018",
    cetagory: "Women's Running Shoes",
    price: "$79.97",
    lessPrice: "$100 ",
    offPrice: "20%",
    img: "/p9/ph1.webp",
  },
  {
    id: 10,
    title: "KD15 'What The'",
    cetagory: "Basketball Shoes",
    price: "$150",
    lessPrice: "",
    offPrice: "",
    img: "/p10/ph1.webp",
  },
  {
    id: 11,
    title: "Air Jordan XXXVII Low",
    cetagory: "Basketball Shoes",
    price: "$175",
    lessPrice: "",
    offPrice: "",
    img: "/p11/ph1.webp",
  },
  {
    id: 12,
    title: "KD14",
    cetagory: "Basketball Shoes",
    price: "$109.97",
    lessPrice: "$150",
    offPrice: "26%",
    img: "/p12/ph1.webp",
  },
];
